// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/inmems3/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFolderRequest) Reset() {
	*x = AddFolderRequest{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFolderRequest) ProtoMessage() {}

func (x *AddFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFolderRequest.ProtoReflect.Descriptor instead.
func (*AddFolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *AddFolderRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AddFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketsLoaded uint32                 `protobuf:"varint,1,opt,name=buckets_loaded,json=bucketsLoaded,proto3" json:"buckets_loaded,omitempty"`
	ObjectsLoaded uint32                 `protobuf:"varint,2,opt,name=objects_loaded,json=objectsLoaded,proto3" json:"objects_loaded,omitempty"`
	BytesLoaded   uint64                 `protobuf:"varint,3,opt,name=bytes_loaded,json=bytesLoaded,proto3" json:"bytes_loaded,omitempty"`
	Buckets       []string               `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFolderResponse) Reset() {
	*x = AddFolderResponse{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFolderResponse) ProtoMessage() {}

func (x *AddFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFolderResponse.ProtoReflect.Descriptor instead.
func (*AddFolderResponse) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *AddFolderResponse) GetBucketsLoaded() uint32 {
	if x != nil {
		return x.BucketsLoaded
	}
	return 0
}

func (x *AddFolderResponse) GetObjectsLoaded() uint32 {
	if x != nil {
		return x.ObjectsLoaded
	}
	return 0
}

func (x *AddFolderResponse) GetBytesLoaded() uint64 {
	if x != nil {
		return x.BytesLoaded
	}
	return 0
}

func (x *AddFolderResponse) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBucketRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type DeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBucketResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ClearAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAllRequest) Reset() {
	*x = ClearAllRequest{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllRequest) ProtoMessage() {}

func (x *ClearAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllRequest.ProtoReflect.Descriptor instead.
func (*ClearAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{4}
}

type ClearAllResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketsDeleted uint32                 `protobuf:"varint,1,opt,name=buckets_deleted,json=bucketsDeleted,proto3" json:"buckets_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearAllResponse) Reset() {
	*x = ClearAllResponse{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllResponse) ProtoMessage() {}

func (x *ClearAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllResponse.ProtoReflect.Descriptor instead.
func (*ClearAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ClearAllResponse) GetBucketsDeleted() uint32 {
	if x != nil {
		return x.BucketsDeleted
	}
	return 0
}

type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{6}
}

type ListBucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []string               `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmems3_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inmems3_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListBucketsResponse) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_proto_inmems3_control_v1_control_proto protoreflect.FileDescriptor

const file_proto_inmems3_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"&proto/inmems3/control/v1/control.proto\x12\x12inmems3.control.v1\"&\n" +
	"\x10AddFolderRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x9e\x01\n" +
	"\x11AddFolderResponse\x12%\n" +
	"\x0ebuckets_loaded\x18\x01 \x01(\rR\rbucketsLoaded\x12%\n" +
	"\x0eobjects_loaded\x18\x02 \x01(\rR\robjectsLoaded\x12!\n" +
	"\fbytes_loaded\x18\x03 \x01(\x04R\vbytesLoaded\x12\x18\n" +
	"\abuckets\x18\x04 \x03(\tR\abuckets\"-\n" +
	"\x13DeleteBucketRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\"0\n" +
	"\x14DeleteBucketResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x11\n" +
	"\x0fClearAllRequest\";\n" +
	"\x10ClearAllResponse\x12'\n" +
	"\x0fbuckets_deleted\x18\x01 \x01(\rR\x0ebucketsDeleted\"\x14\n" +
	"\x12ListBucketsRequest\"/\n" +
	"\x13ListBucketsResponse\x12\x18\n" +
	"\abuckets\x18\x01 \x03(\tR\abuckets2\x84\x03\n" +
	"\x0eControlService\x12X\n" +
	"\tAddFolder\x12$.inmems3.control.v1.AddFolderRequest\x1a%.inmems3.control.v1.AddFolderResponse\x12a\n" +
	"\fDeleteBucket\x12'.inmems3.control.v1.DeleteBucketRequest\x1a(.inmems3.control.v1.DeleteBucketResponse\x12U\n" +
	"\bClearAll\x12#.inmems3.control.v1.ClearAllRequest\x1a$.inmems3.control.v1.ClearAllResponse\x12^\n" +
	"\vListBuckets\x12&.inmems3.control.v1.ListBucketsRequest\x1a'.inmems3.control.v1.ListBucketsResponseBAZ?rdma-demo/server-client-demo/proto/inmems3/control/v1;controlv1b\x06proto3"

var (
	file_proto_inmems3_control_v1_control_proto_rawDescOnce sync.Once
	file_proto_inmems3_control_v1_control_proto_rawDescData []byte
)

func file_proto_inmems3_control_v1_control_proto_rawDescGZIP() []byte {
	file_proto_inmems3_control_v1_control_proto_rawDescOnce.Do(func() {
		file_proto_inmems3_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inmems3_control_v1_control_proto_rawDesc), len(file_proto_inmems3_control_v1_control_proto_rawDesc)))
	})
	return file_proto_inmems3_control_v1_control_proto_rawDescData
}

var file_proto_inmems3_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_inmems3_control_v1_control_proto_goTypes = []any{
	(*AddFolderRequest)(nil),     // 0: inmems3.control.v1.AddFolderRequest
	(*AddFolderResponse)(nil),    // 1: inmems3.control.v1.AddFolderResponse
	(*DeleteBucketRequest)(nil),  // 2: inmems3.control.v1.DeleteBucketRequest
	(*DeleteBucketResponse)(nil), // 3: inmems3.control.v1.DeleteBucketResponse
	(*ClearAllRequest)(nil),      // 4: inmems3.control.v1.ClearAllRequest
	(*ClearAllResponse)(nil),     // 5: inmems3.control.v1.ClearAllResponse
	(*ListBucketsRequest)(nil),   // 6: inmems3.control.v1.ListBucketsRequest
	(*ListBucketsResponse)(nil),  // 7: inmems3.control.v1.ListBucketsResponse
}
var file_proto_inmems3_control_v1_control_proto_depIdxs = []int32{
	0, // 0: inmems3.control.v1.ControlService.AddFolder:input_type -> inmems3.control.v1.AddFolderRequest
	2, // 1: inmems3.control.v1.ControlService.DeleteBucket:input_type -> inmems3.control.v1.DeleteBucketRequest
	4, // 2: inmems3.control.v1.ControlService.ClearAll:input_type -> inmems3.control.v1.ClearAllRequest
	6, // 3: inmems3.control.v1.ControlService.ListBuckets:input_type -> inmems3.control.v1.ListBucketsRequest
	1, // 4: inmems3.control.v1.ControlService.AddFolder:output_type -> inmems3.control.v1.AddFolderResponse
	3, // 5: inmems3.control.v1.ControlService.DeleteBucket:output_type -> inmems3.control.v1.DeleteBucketResponse
	5, // 6: inmems3.control.v1.ControlService.ClearAll:output_type -> inmems3.control.v1.ClearAllResponse
	7, // 7: inmems3.control.v1.ControlService.ListBuckets:output_type -> inmems3.control.v1.ListBucketsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inmems3_control_v1_control_proto_init() }
func file_proto_inmems3_control_v1_control_proto_init() {
	if File_proto_inmems3_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inmems3_control_v1_control_proto_rawDesc), len(file_proto_inmems3_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inmems3_control_v1_control_proto_goTypes,
		DependencyIndexes: file_proto_inmems3_control_v1_control_proto_depIdxs,
		MessageInfos:      file_proto_inmems3_control_v1_control_proto_msgTypes,
	}.Build()
	File_proto_inmems3_control_v1_control_proto = out.File
	file_proto_inmems3_control_v1_control_proto_goTypes = nil
	file_proto_inmems3_control_v1_control_proto_depIdxs = nil
}
